import { useState, useMemo, useEffect, useRef } from 'react'
import { motion, AnimatePresence, useScroll, useSpring } from 'framer-motion'
import { Link, useNavigate } from 'react-router-dom'
import { useDebt } from '../context/DebtContext'
import { formatCurrency } from '../utils/debtCalculator'
import GlowCard from '../components/GlowCard'
import {
    LineChart,
    Line,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
    Legend,
    Area,
    AreaChart
} from 'recharts'
import confetti from 'canvas-confetti'

const MilestoneRow = ({ icon, text, type, progress }) => (
    <tr className="bg-primary/10 border-y border-dashed border-primary/40">
        <td colSpan={7} className="px-6 py-4">
            <motion.div
                initial={{ scale: 0.8, opacity: 0 }}
                whileInView={{ scale: 1, opacity: 1 }}
                viewport={{ once: true }}
                className="flex items-center justify-center gap-4 py-2"
            >
                <span className={`w-3 h-3 rounded-full shadow-lg ${type === 'purple' ? 'bg-primary shadow-purple-glow' :
                    type === 'orange' ? 'bg-orange-500 shadow-orange-glow' : 'bg-success shadow-green-glow'
                    }`}></span>
                <span className="text-2xl">{icon}</span>
                <span className="font-bold text-white tracking-wide">{text}</span>
                <span className="pill-badge text-[10px] bg-primary/20 border-primary/40">MILESTONE</span>
            </motion.div>
        </td>
    </tr>
)

const EscapePlan = () => {
    const navigate = useNavigate()
    const { cards, monthlyPayment, strategy, setStrategy, results } = useDebt()
    const { escapePlan } = results
    const [toast, setToast] = useState(null)

    // Sync state with content if needed
    useEffect(() => {
        if (cards.length === 0) {
            navigate('/input')
        }
    }, [cards, navigate])

    const handleStrategyToggle = (newStrategy) => {
        setStrategy(newStrategy)
    }

    const triggerConfetti = () => {
        confetti({
            particleCount: 150,
            spread: 70,
            origin: { y: 0.6 },
            colors: ['#7B2FFF', '#00FF88', '#FF4444', '#FFFFFF']
        })
    }

    const handleCopySummary = () => {
        const text = `My DebtFree Plan:
Debt Free By: ${escapePlan.payoffDate}
Total Months: ${escapePlan.totalMonths}
I will save ${formatCurrency(escapePlan.moneySaved)} vs minimum payments.
Generated by DebtFree.`

        navigator.clipboard.writeText(text)
        setToast('✅ Copied to clipboard!')
        setTimeout(() => setToast(null), 3000)
    }

    // Chart Data Preparation
    const chartData = useMemo(() => {
        if (!escapePlan) return []
        const data = []
        const maxMonths = Math.max(escapePlan.totalMonths, Math.min(escapePlan.minScenarioMonths, 120))

        for (let i = 0; i <= maxMonths; i++) {
            data.push({
                month: i,
                planBalance: escapePlan.schedule.find(s => s.month === i)?.remainingBalance ?? (i > escapePlan.totalMonths ? 0 : escapePlan.initialTotalDebt),
                minBalance: escapePlan.minScenarioSchedule.find(s => s.month === i)?.remainingBalance ?? (i > escapePlan.minScenarioMonths ? 0 : escapePlan.initialTotalDebt)
            })
        }
        // Fix i=0
        data[0] = { month: 0, planBalance: escapePlan.initialTotalDebt, minBalance: escapePlan.initialTotalDebt }
        return data
    }, [escapePlan])

    // Scroll Progress Logic for Sticky Side
    const containerRef = useRef(null)
    const [currentMonthIdx, setCurrentMonthIdx] = useState(0)
    const { scrollYProgress } = useScroll()
    const scaleX = useSpring(scrollYProgress, {
        stiffness: 100,
        damping: 30,
        restDelta: 0.001
    })

    // Update current month based on scroll
    useEffect(() => {
        const handleScroll = () => {
            if (!escapePlan) return
            const scrollPercent = window.scrollY / (document.documentElement.scrollHeight - window.innerHeight)
            const monthIdx = Math.min(
                Math.floor(scrollPercent * escapePlan.schedule.length),
                escapePlan.schedule.length - 1
            )
            setCurrentMonthIdx(Math.max(0, monthIdx))
        }
        window.addEventListener('scroll', handleScroll)
        return () => window.removeEventListener('scroll', handleScroll)
    }, [escapePlan])

    if (!escapePlan) return null

    return (
        <div className="relative min-h-screen bg-[#0A0A0F]" ref={containerRef}>
            {/* Background Glow */}
            <div className="fixed inset-0 bg-gradient-to-b from-[#0A0A2E]/50 to-[#0A0A0F] -z-10"></div>
            <div className="fixed top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-96 bg-primary/10 blur-[150px] -z-10 rounded-full"></div>

            {/* Main Container */}
            <div className="max-w-7xl mx-auto px-6 py-12 pb-40">

                {/* Header Section */}
                <header className="mb-16">
                    <Link to="/dashboard" className="ghost-btn inline-flex items-center gap-2 mb-8 group">
                        <span className="transition-transform group-hover:-translate-x-1">←</span> Back to Dashboard
                    </Link>

                    <div className="text-center">
                        <motion.h1
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="text-4xl md:text-6xl font-bold mb-6 relative inline-block"
                        >
                            Your Personal Escape Plan
                            <motion.span
                                initial={{ width: 0 }}
                                animate={{ width: '100%' }}
                                transition={{ delay: 0.5, duration: 1 }}
                                className="absolute -bottom-2 left-0 h-1.5 bg-success shadow-green-glow rounded-full"
                            ></motion.span>
                        </motion.h1>
                        <p className="text-text-secondary text-lg mt-6">
                            Follow this plan every month and you will be completely debt free by <span className="text-success font-bold shadow-green-glow px-1"> {escapePlan.payoffDate}</span>
                        </p>
                    </div>
                </header>

                {/* Section 1: Summary Box */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 }}
                    className="glow-card border-success/30 p-8 mb-16"
                >
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 mb-8">
                        <div className="text-center">
                            <span className="text-3xl mb-2 block">🏆</span>
                            <p className="text-xs text-text-secondary uppercase tracking-widest mb-1">Debt Free By</p>
                            <p className="text-2xl md:text-3xl font-black text-success shadow-green-glow">{escapePlan.payoffDate}</p>
                        </div>
                        <div className="text-center">
                            <span className="text-3xl mb-2 block">📅</span>
                            <p className="text-xs text-text-secondary uppercase tracking-widest mb-1">Total Months</p>
                            <p className="text-2xl md:text-3xl font-black">{escapePlan.totalMonths} <span className="text-sm text-text-secondary">months</span></p>
                        </div>
                        <div className="text-center">
                            <span className="text-3xl mb-2 block">💳</span>
                            <p className="text-xs text-text-secondary uppercase tracking-widest mb-1">Total You Will Pay</p>
                            <p className="text-2xl md:text-3xl font-black truncate">{formatCurrency(escapePlan.totalAmountPaid)}</p>
                        </div>
                        <div className="text-center">
                            <span className="text-3xl mb-2 block">💰</span>
                            <p className="text-xs text-text-secondary uppercase tracking-widest mb-1">You Save vs Min</p>
                            <p className="text-2xl md:text-3xl font-black text-success shadow-green-glow">{formatCurrency(escapePlan.moneySaved)}</p>
                        </div>
                    </div>

                    <div className="h-px bg-primary/20 shadow-purple-glow w-full mb-6"></div>

                    <p className="text-center text-text-secondary text-sm italic">
                        If you had only paid the minimum due every month, you would have been trapped for
                        <span className="text-white font-bold mx-1">{Math.floor(escapePlan.minScenarioMonths / 12)}y {escapePlan.minScenarioMonths % 12}m</span>
                        and paid <span className="text-danger font-bold mx-1">{formatCurrency(escapePlan.minScenarioInterest)}</span> extra in interest alone.
                    </p>
                </motion.div>

                {/* Section 2: Strategy Toggle */}
                <div className="flex flex-col items-center mb-16">
                    <p className="text-text-secondary text-xs uppercase tracking-widest mb-4">Choose your payoff strategy:</p>
                    <div className="bg-white/5 p-1 rounded-full border border-primary/30 flex items-center relative mb-8">
                        <motion.div
                            layoutId="toggle-bg"
                            className="absolute h-[calc(100%-8px)] rounded-full bg-primary shadow-purple-glow"
                            initial={false}
                            animate={{
                                left: strategy === 'avalanche' ? '4px' : 'calc(50% + 2px)',
                                width: 'calc(50% - 6px)'
                            }}
                            transition={{ type: "spring", stiffness: 300, damping: 30 }}
                        />
                        <button
                            onClick={() => handleStrategyToggle('avalanche')}
                            className={`relative z-10 px-8 py-3 rounded-full text-sm font-bold transition-colors w-44 ${strategy === 'avalanche' ? 'text-white' : 'text-text-secondary'
                                }`}
                        >
                            ⚡ Avalanche Method
                        </button>
                        <button
                            onClick={() => handleStrategyToggle('snowball')}
                            className={`relative z-10 px-8 py-3 rounded-full text-sm font-bold transition-colors w-44 ${strategy === 'snowball' ? 'text-white' : 'text-text-secondary'
                                }`}
                        >
                            ❄️ Snowball Method
                        </button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-full max-w-4xl">
                        <GlowCard className={`border-primary/20 ${strategy === 'avalanche' ? 'bg-primary/5 border-primary/60' : ''}`}>
                            <h4 className="font-bold flex items-center gap-2 mb-2">⚡ Avalanche Method</h4>
                            <p className="text-text-secondary text-xs leading-relaxed mb-4">
                                Pay off the card with the highest interest rate first while paying minimums on others.
                                This saves you the most money in total interest.
                            </p>
                            <span className="pill-badge text-[9px] text-success border-success/30">💰 Best for saving money</span>
                        </GlowCard>
                        <GlowCard className={`border-primary/20 ${strategy === 'snowball' ? 'bg-primary/5 border-primary/60' : ''}`}>
                            <h4 className="font-bold flex items-center gap-2 mb-2">❄️ Snowball Method</h4>
                            <p className="text-text-secondary text-xs leading-relaxed mb-4">
                                Pay off the card with the lowest balance first while paying minimums on others.
                                Gives you quick wins and builds momentum.
                            </p>
                            <span className="pill-badge text-[9px] text-primary border-primary/30">🧠 Best for motivation</span>
                        </GlowCard>
                    </div>
                </div>

                {/* Section 3: Payment Table */}
                <section className="mb-20">
                    <div className="mb-8">
                        <h2 className="text-2xl font-bold mb-2">Your Month-by-Month Roadmap</h2>
                        <p className="text-text-secondary text-sm">Every row is one month closer to financial freedom.</p>
                    </div>

                    <div className="glow-card p-0 overflow-hidden relative border-primary/20">
                        <div className="overflow-x-auto max-h-[800px] overflow-y-auto custom-scrollbar">
                            <table className="w-full text-left border-collapse table-fixed min-w-[800px]">
                                <thead className="sticky top-0 z-30 bg-[#1A0A2E] text-white">
                                    <tr className="border-b border-primary/30">
                                        <th className="px-6 py-5 font-bold w-12 bg-[#1A0A2E] sticky left-0 z-40">#</th>
                                        <th className="px-6 py-5 font-bold">Month</th>
                                        <th className="px-6 py-5 font-bold text-right">Payment</th>
                                        <th className="px-6 py-5 font-bold text-right">Interest Paid</th>
                                        <th className="px-6 py-5 font-bold text-right">Principal Cleared</th>
                                        <th className="px-6 py-5 font-bold text-right">Balance Remaining</th>
                                        <th className="px-6 py-5 font-bold">Progress</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-white/5">
                                    {escapePlan.schedule.map((row, idx) => {
                                        const totalRows = escapePlan.schedule.length
                                        const progress = idx / totalRows
                                        const isLast = idx === totalRows - 1

                                        // Row Tints
                                        let tintClass = ''
                                        let borderClass = ''
                                        if (progress < 0.33) {
                                            tintClass = 'bg-danger/5 hover:bg-danger/10'
                                            borderClass = 'border-l-2 border-danger/40'
                                        } else if (progress < 0.66) {
                                            tintClass = 'bg-orange-500/5 hover:bg-orange-500/10'
                                            borderClass = 'border-l-2 border-orange-500/40'
                                        } else {
                                            tintClass = 'bg-success/5 hover:bg-success/10'
                                            borderClass = 'border-l-2 border-success/30'
                                        }

                                        if (isLast) {
                                            tintClass = 'bg-success/20 animate-pulse'
                                            borderClass = 'border-l-4 border-success shadow-green-glow'
                                        }

                                        return (
                                            <>
                                                {/* Milestones */}
                                                {idx === Math.floor(totalRows * 0.25) && (
                                                    <MilestoneRow icon="🎉" text="25% of your debt is gone! You are doing amazing!" type="purple" />
                                                )}
                                                {idx === Math.floor(totalRows * 0.5) && (
                                                    <MilestoneRow icon="💪" text="HALFWAY THERE! You have cleared half your debt!" type="orange" />
                                                )}
                                                {idx === Math.floor(totalRows * 0.75) && (
                                                    <MilestoneRow icon="🔥" text="Final Stretch! Only 25% left. The end is near!" type="green" />
                                                )}

                                                <motion.tr
                                                    key={idx}
                                                    initial={{ opacity: 0, x: -20 }}
                                                    whileInView={{ opacity: 1, x: 0 }}
                                                    viewport={{ once: true }}
                                                    transition={{ delay: Math.min(idx * 0.03, 1) }}
                                                    className={`${tintClass} ${borderClass} transition-colors group`}
                                                >
                                                    <td className={`px-6 py-4 text-xs text-text-secondary sticky left-0 z-20 ${tintClass} group-hover:bg-white/10`}>
                                                        {idx + 1}
                                                    </td>
                                                    <td className="px-6 py-4 text-sm font-medium">
                                                        {new Date(new Date().setMonth(new Date().getMonth() + idx)).toLocaleDateString('en-IN', { month: 'short', year: 'numeric' })}
                                                    </td>
                                                    <td className="px-6 py-4 text-sm font-bold text-white text-right">
                                                        {formatCurrency(row.payment)}
                                                    </td>
                                                    <td className="px-6 py-4 text-sm text-danger text-right">
                                                        {formatCurrency(row.interestPaid)}
                                                    </td>
                                                    <td className="px-6 py-4 text-sm text-success text-right">
                                                        {formatCurrency(row.principalPaid)}
                                                    </td>
                                                    <td className={`px-6 py-4 text-sm font-bold text-right ${isLast ? 'text-success' : 'text-white'}`}>
                                                        {isLast ? '🏆 ₹0 — DEBT FREE!' : formatCurrency(row.remainingBalance)}
                                                    </td>
                                                    <td className="px-6 py-4">
                                                        <div className="w-full bg-white/10 h-1.5 rounded-full overflow-hidden">
                                                            <motion.div
                                                                initial={{ width: 0 }}
                                                                whileInView={{ width: `${row.progress}%` }}
                                                                viewport={{ once: true }}
                                                                transition={{ duration: 1, ease: "easeOut" }}
                                                                className="h-full bg-primary shadow-purple-glow"
                                                            />
                                                        </div>
                                                    </td>
                                                </motion.tr>
                                            </>
                                        )
                                    })}
                                </tbody>
                            </table>
                        </div>

                        {/* Final Celebration Trigger */}
                        <motion.div
                            onViewportEnter={triggerConfetti}
                            className="absolute bottom-0 w-full h-1"
                        />
                    </div>
                </section>

                {/* Section 5: Progress Chart */}
                <section className="mb-20">
                    <div className="mb-8">
                        <h2 className="text-2xl font-bold mb-2">Watch Your Debt Disappear</h2>
                        <p className="text-text-secondary text-sm">The red line shows minimum payments. The green line is your escape plan.</p>
                    </div>

                    <GlowCard className="p-8 h-[450px]">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={chartData}>
                                <defs>
                                    <linearGradient id="colorMin" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#FF4444" stopOpacity={0.1} />
                                        <stop offset="95%" stopColor="#FF4444" stopOpacity={0} />
                                    </linearGradient>
                                    <linearGradient id="colorPlan" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#00FF88" stopOpacity={0.1} />
                                        <stop offset="95%" stopColor="#00FF88" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <CartesianGrid strokeDasharray="3 3" stroke="rgba(123,47,255,0.15)" vertical={false} />
                                <XAxis
                                    dataKey="month"
                                    stroke="#A89EC9"
                                    fontSize={12}
                                    tick={{ fill: '#A89EC9' }}
                                    label={{ value: 'Months', position: 'insideBottom', offset: -5, fill: '#A89EC9' }}
                                />
                                <YAxis
                                    stroke="#A89EC9"
                                    fontSize={12}
                                    tick={{ fill: '#A89EC9' }}
                                    tickFormatter={val => `₹${(val / 100000).toFixed(1)}L`}
                                    label={{ value: 'Balance', angle: -90, position: 'insideLeft', fill: '#A89EC9' }}
                                />
                                <Tooltip
                                    contentStyle={{ backgroundColor: 'rgba(10, 10, 15, 0.95)', border: '1px solid rgba(123,47,255,0.3)', borderRadius: '12px' }}
                                    formatter={(val) => formatCurrency(val)}
                                />
                                <Legend />
                                <Area
                                    type="monotone"
                                    dataKey="minBalance"
                                    name="Minimum Only"
                                    stroke="#FF4444"
                                    strokeDasharray="5 5"
                                    strokeWidth={2}
                                    fillOpacity={1}
                                    fill="url(#colorMin)"
                                />
                                <Area
                                    type="monotone"
                                    dataKey="planBalance"
                                    name="Your Plan"
                                    stroke="#00FF88"
                                    strokeWidth={3}
                                    fillOpacity={1}
                                    fill="url(#colorPlan)"
                                />
                            </AreaChart>
                        </ResponsiveContainer>
                    </GlowCard>
                </section>

                {/* Section 6: Card Breakdown */}
                {cards.length >= 2 && (
                    <section className="mb-20">
                        <div className="mb-8">
                            <h2 className="text-2xl font-bold mb-2">Card-by-Card Payoff Order</h2>
                            <p className="text-text-secondary text-sm">
                                {strategy === 'avalanche' ? 'Paying highest interest cards first' : 'Paying lowest balance cards first'}
                            </p>
                        </div>

                        <div className="space-y-4">
                            {[...cards]
                                .sort((a, b) => strategy === 'avalanche' ? b.interestRate - a.interestRate : a.balance - b.balance)
                                .map((card, idx) => (
                                    <motion.div
                                        key={card.id}
                                        initial={{ opacity: 0, x: -20 }}
                                        whileInView={{ opacity: 1, x: 0 }}
                                        transition={{ delay: idx * 0.1 }}
                                        className="glow-card border-white/5 p-6 flex flex-col md:flex-row items-center justify-between gap-6"
                                    >
                                        <div className="flex items-center gap-6">
                                            <div className="w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center font-black text-primary border border-primary/40 shadow-purple-glow">
                                                {idx + 1}{idx === 0 ? 'st' : idx === 1 ? 'nd' : idx === 2 ? 'rd' : 'th'}
                                            </div>
                                            <div>
                                                <h4 className="text-xl font-bold">{card.name}</h4>
                                                <p className="text-xs text-text-secondary uppercase tracking-widest">Priority #{idx + 1}</p>
                                            </div>
                                        </div>

                                        <div className="flex flex-wrap gap-8 text-center md:text-left">
                                            <div>
                                                <p className="text-[10px] text-text-secondary uppercase">Balance</p>
                                                <p className="font-bold">{formatCurrency(card.balance)}</p>
                                            </div>
                                            <div>
                                                <p className="text-[10px] text-text-secondary uppercase">Rate</p>
                                                <p className="font-bold">{card.interestRate}%/mo</p>
                                            </div>
                                        </div>

                                        <div className="text-center md:text-right">
                                            <p className="text-[10px] text-text-secondary uppercase">Target Date</p>
                                            <p className="text-lg font-bold text-success shadow-green-glow">
                                                {escapePlan.cardPayoffDates.find(d => d.id === card.id)?.payoffDate}
                                            </p>
                                        </div>
                                    </motion.div>
                                ))}
                        </div>
                    </section>
                )}

                {/* Section 7: Download & Share */}
                <section className="mb-20 flex justify-center">
                    <GlowCard className="max-w-2xl w-full p-10 text-center border-primary/30">
                        <h3 className="text-2xl font-bold mb-3">Save Your Plan</h3>
                        <p className="text-text-secondary text-sm mb-10">Download your plan and check off each month as you pay.</p>

                        <div className="flex flex-col md:flex-row gap-4 justify-center">
                            <button
                                onClick={() => window.print()}
                                className="glow-btn px-10 py-4 text-base"
                            >
                                📄 Download as PDF
                            </button>
                            <button
                                onClick={handleCopySummary}
                                className="ghost-btn px-10 py-4 text-base relative"
                            >
                                📋 Copy Summary
                                {toast && (
                                    <motion.span
                                        initial={{ opacity: 0, y: 10 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        className="absolute -top-12 left-1/2 -translate-x-1/2 bg-success text-black px-4 py-2 rounded-lg text-xs font-bold whitespace-nowrap"
                                    >
                                        {toast}
                                    </motion.span>
                                )}
                            </button>
                        </div>
                    </GlowCard>
                </section>

                {/* Section 8: Bottom CTA */}
                <section className="text-center py-20 relative overflow-hidden rounded-3xl">
                    <div className="absolute inset-0 bg-primary/5 -z-10"></div>
                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-full bg-primary/10 blur-[100px] rounded-full -z-20"></div>

                    <h2 className="text-3xl md:text-5xl font-bold mb-6">Want to Get Free Even Faster?</h2>
                    <p className="text-text-secondary text-lg mb-10 max-w-2xl mx-auto">
                        See what happens when you pay just a little more each month.
                        Small changes create massive results.
                    </p>

                    <div className="flex flex-col md:flex-row gap-6 justify-center px-6">
                        <Link to="/simulator" className="glow-btn px-12 py-5 text-lg">
                            ⚡ Try the What-If Simulator →
                        </Link>
                        <Link to="/dashboard" className="ghost-btn px-12 py-5 text-lg">
                            🏠 Back to Dashboard
                        </Link>
                    </div>
                </section>
            </div>

            {/* Sticky Side Element (Desktop Only) */}
            <div className="hidden lg:block fixed right-12 top-1/2 -translate-y-1/2 z-50">
                <GlowCard className="w-64 p-6 border-primary/30 bg-[#0A0A0F]/80 backdrop-blur-xl">
                    <div className="mb-4">
                        <p className="text-[10px] text-text-secondary uppercase mb-2">
                            📍 You are viewing {currentMonthIdx === escapePlan.schedule.length - 1 ? 'the end' : `Month ${currentMonthIdx + 1}`}
                        </p>
                        <div className="h-2 w-full bg-white/10 rounded-full overflow-hidden mb-2">
                            <motion.div
                                style={{ scaleX }}
                                className="h-full bg-primary shadow-purple-glow origin-left"
                            />
                        </div>
                        <p className="text-lg font-bold text-white">
                            {formatCurrency(escapePlan.schedule[currentMonthIdx]?.remainingBalance || 0)}
                        </p>
                        <p className="text-[8px] text-text-secondary uppercase">Remaining at this point</p>
                    </div>
                    <p className="text-xs text-text-secondary">
                        You're viewing the roadmap to <span className="text-success font-bold">Freedom</span>.
                    </p>
                </GlowCard>
            </div>

            {/* Global CSS for Print */}
            <style>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 0px;
          height: 0px;
        }
        @media print {
          nav, footer, .glow-btn, .ghost-btn, .fixed, .Link, a {
            display: none !important;
          }
          body {
            background: white !important;
            color: black !important;
          }
          .glow-card {
            border: 1px solid #eee !important;
            background: white !important;
            box-shadow: none !important;
            color: black !important;
          }
          .text-primary, .text-success, .text-danger, .text-text-secondary {
            color: black !important;
          }
          table {
            color: black !important;
            border: 1px solid #eee !important;
            min-width: 100% !important;
          }
          th {
            background: #eee !important;
            color: black !important;
          }
          tr {
            background: white !important;
            border-bottom: 1px solid #eee !important;
          }
          .shadow-green-glow, .shadow-purple-glow {
            box-shadow: none !important;
          }
        }
      `}</style>
        </div>
    )
}

export default EscapePlan
